import React, { useMemo, useState } from 'react'
import { Check, Copy, Download, FileBarChart } from 'lucide-react'
import EmployerModal from '../EmployerModal'
import { whatsWorking, retentionRiskForecast } from '../../../data/analyticsData'

function buildSummaryText(summary, sourceROI) {
  const lines = []
  lines.push(`LEADERSHIP SUMMARY — ${summary.period}`)
  lines.push('Acme Corporation · Talent Acquisition · Generated by CareerOS')
  lines.push('')
  lines.push('KEY METRICS')
  summary.metrics.forEach((m) => lines.push(`- ${m.label}: ${m.value} (${m.note})`))
  lines.push('')
  lines.push("WHAT'S WORKING")
  lines.push(whatsWorking.body)
  lines.push('')
  whatsWorking.highlights.forEach((h) => lines.push(`- ${h.label}: ${h.title} — ${h.detail}`))
  lines.push('')
  lines.push('SOURCE ROI (cost per qualified candidate)')
  sourceROI.forEach((s) => lines.push(`- ${s.label}: ${s.cost}, ${s.retention}`))
  lines.push('')
  lines.push('RETENTION RISK — CURRENT PIPELINE')
  retentionRiskForecast.forEach((c) => lines.push(`- ${c.name} (${c.roleFit}): ${c.risk} risk — ${c.conditions}`))
  lines.push('')
  lines.push('Prepared by CareerOS AI — every figure above is traceable to underlying candidate and engagement evidence.')
  return lines.join('\n')
}

export default function ExportSummaryModal({ summary, sourceROI, onClose, onToast }) {
  const [copied, setCopied] = useState(false)
  const text = useMemo(() => buildSummaryText(summary, sourceROI), [summary, sourceROI])

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      // Clipboard API unavailable — text is still visible for manual copy.
    }
    setCopied(true)
    onToast?.('Summary copied to clipboard')
    window.setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `careeros-leadership-summary-${summary.period.split(' ')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    onToast?.('Summary downloaded')
  }

  return (
    <EmployerModal
      title="Export for leadership"
      icon={<FileBarChart className="h-4 w-4" />}
      onClose={onClose}
      maxWidth="max-w-[600px]"
      footer={
        <div className="flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className={`flex items-center gap-1.5 rounded-full px-4 py-2 text-sm font-semibold transition-colors ${
              copied ? 'bg-green-600 text-white' : 'employer-secondary-button'
            }`}
          >
            {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-1.5 rounded-full bg-[#185FA5] px-4 py-2 text-sm font-semibold text-white hover:bg-[#134c87]"
          >
            <Download className="h-3.5 w-3.5" />
            Download .txt
          </button>
        </div>
      }
    >
      <p className="mb-3 text-xs text-gray-400">Formatted for pasting into Slack, email, or a leadership deck — no design tool needed.</p>
      <pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-[13px] leading-6 text-slate-800 ring-1 ring-slate-100">{text}</pre>
    </EmployerModal>
  )
}
