import React from 'react'

export default function AIProposalCard({ points }) {
  return (
    <section className="rounded-2xl border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-blue-50 p-5">
      <div className="mb-4 flex items-center gap-2">
        <h3 className="text-sm font-semibold text-slate-950">AI-Generated Collaboration Proposal</h3>
        <span className="rounded-full bg-violet-100 px-2.5 py-1 text-xs font-semibold text-violet-700">Preview</span>
      </div>
      <p className="text-sm leading-6 text-slate-600">
        Based on the event needs and company offerings, we recommend a collaboration structure that maximizes student impact and company engagement.
      </p>
      <div className="mt-4 space-y-2">
        {points.map((point) => (
          <p key={point} className="flex gap-3 text-sm leading-6 text-slate-700">
            <span className="mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-indigo-600 text-[10px] font-bold text-white">OK</span>
            <span>{point}</span>
          </p>
        ))}
      </div>
      <p className="mt-4 text-xs font-semibold text-violet-600">Generated by CareerOS AI</p>
    </section>
  )
}
