export const accreditationSummary = {
  banner:
    'QS World Rankings submission is due in 6 weeks. 41 of 50 required evidence points are ready, 7 are in progress, and 2 are missing data. I can generate a draft submission pack now.',
  kpis: [
    { id: 'readiness', label: 'Overall readiness', value: '82%', note: 'Across all active submissions', tone: 'green' },
    { id: 'ready', label: 'Evidence ready', value: '41', note: 'Of 50 required', tone: 'green' },
    { id: 'progress', label: 'In progress', value: '7', note: 'Need updating', tone: 'orange' },
    { id: 'missing', label: 'Missing data', value: '2', note: 'Action needed', tone: 'red' },
  ],
}

export const requirementGroups = [
  {
    id: 'graduate-employability',
    index: 1,
    title: 'Graduate Employability',
    progress: '12/15 ready',
    items: [
      { id: 'employment-rate', name: 'Employment rate within 6 months', status: 'ready', frameworks: ['QS', 'MQA'] },
      { id: 'starting-salary', name: 'Average starting salary by program', status: 'ready', frameworks: ['QS'] },
      { id: 'employer-satisfaction', name: 'Employer satisfaction scores', status: 'ready', frameworks: ['QS', 'AACSB'] },
      { id: 'graduate-destination', name: 'Graduate destination breakdown', status: 'in-progress', frameworks: ['QS', 'MQA'] },
      { id: 'career-progression', name: 'Alumni 5-year career progression', status: 'missing', frameworks: ['MQA'] },
    ],
  },
  {
    id: 'industry-alignment',
    index: 2,
    title: 'Industry Alignment',
    progress: '14/18 ready',
    items: [
      { id: 'partner-coverage', name: 'Industry partner coverage', status: 'ready', frameworks: ['QS', 'AACSB'] },
      { id: 'market-demand', name: 'Market demand evidence', status: 'ready', frameworks: ['MQA'] },
      { id: 'advisory-feedback', name: 'Advisory board feedback loop', status: 'in-progress', frameworks: ['MQA', 'AACSB'] },
      { id: 'curriculum-evidence-packs', name: 'Curriculum-market gap evidence packs', status: 'missing', frameworks: ['MQA'] },
    ],
  },
  {
    id: 'student-support',
    index: 3,
    title: 'Student Support Services',
    progress: '15/17 ready',
    items: [
      { id: 'intervention-records', name: 'Intervention records and outcomes', status: 'ready', frameworks: ['MQA'] },
      { id: 'career-service-usage', name: 'Career service usage trends', status: 'ready', frameworks: ['QS'] },
      { id: 'support-feedback', name: 'Student support satisfaction', status: 'in-progress', frameworks: ['AACSB'] },
    ],
  },
]

export const evidenceByRequirement = {
  'graduate-destination': {
    status: 'in-progress',
    requiredBy: 'QS World Rankings, MQA Self-Review',
    completeness: 67,
    readySources: 2,
    totalSources: 3,
    sources: [
      {
        id: 'alumni-pathway',
        label: 'From: Alumni Signal Intelligence',
        sourcePage: '/university/alumni-signals',
        title: 'Graduate Role Pathway data - 412 tracked alumni, 78% response rate',
        updated: 'Last updated: 2 days ago',
        status: 'ready',
        action: 'View source',
        icon: 'trend',
      },
      {
        id: 'partnerships',
        label: 'From: Collaboration Marketplace',
        sourcePage: '/university/collaboration',
        title: 'Partnership hiring conversion data - 12 active partnerships',
        updated: 'Last updated: 5 days ago',
        status: 'ready',
        action: 'View source',
        icon: 'handshake',
      },
      {
        id: 'international-placement',
        label: 'Missing: International placement data',
        sourcePage: null,
        title: '3 of 5 years of international destination data not yet collected',
        updated: 'Last updated: N/A',
        status: 'missing',
        action: 'Request data',
        icon: 'warning',
      },
    ],
  },
  'employment-rate': {
    status: 'ready',
    requiredBy: 'QS World Rankings, MQA Self-Review',
    completeness: 100,
    readySources: 2,
    totalSources: 2,
    sources: [
      {
        id: 'alumni-employment',
        label: 'From: Alumni Signal Intelligence',
        sourcePage: '/university/alumni-signals',
        title: 'Time-to-first-role tracking - 2.3 months average, 412 tracked alumni',
        updated: 'Last updated: 2 days ago',
        status: 'ready',
        action: 'View source',
        icon: 'trend',
      },
      {
        id: 'tracer-study',
        label: 'From: Internal Graduate Tracer Study',
        sourcePage: null,
        title: 'Annual employment status survey, 6-month post-graduation checkpoint',
        updated: 'Last updated: 1 week ago',
        status: 'ready',
        action: 'View source',
        icon: 'check',
      },
    ],
  },
  'career-progression': {
    status: 'missing',
    requiredBy: 'MQA Self-Review',
    completeness: 20,
    readySources: 0,
    totalSources: 2,
    sources: [
      {
        id: 'longitudinal-tracking',
        label: 'Missing: 5-year longitudinal alumni tracking',
        sourcePage: null,
        title: 'Alumni Signal Intelligence currently tracks 2-3 year outcomes only — 5-year data not yet collected',
        updated: 'Last updated: N/A',
        status: 'missing',
        action: 'Request data',
        icon: 'warning',
      },
      {
        id: 'promotion-records',
        label: 'Missing: Employer-reported promotion records',
        sourcePage: null,
        title: 'No structured mechanism currently exists to capture alumni promotions post-hire',
        updated: 'Last updated: N/A',
        status: 'missing',
        action: 'Request data',
        icon: 'warning',
      },
    ],
  },
  'market-demand': {
    status: 'ready',
    requiredBy: 'MQA Self-Review',
    completeness: 100,
    readySources: 2,
    totalSources: 2,
    sources: [
      {
        id: 'curriculum-gap-quadrant',
        label: 'From: Curriculum-Market Alignment',
        sourcePage: '/university/curriculum-alignment',
        title: 'Gap Overview quadrant - 7 skill nodes mapped against 90-day job posting demand',
        updated: 'Last updated: 3 days ago',
        status: 'ready',
        action: 'View source',
        icon: 'trend',
      },
      {
        id: 'employer-language',
        label: 'From: Curriculum-Market Alignment',
        sourcePage: '/university/curriculum-alignment',
        title: 'Employer job-posting language analysis - 127 postings analyzed, last 90 days',
        updated: 'Last updated: 3 days ago',
        status: 'ready',
        action: 'View source',
        icon: 'trend',
      },
    ],
  },
  'intervention-records': {
    status: 'ready',
    requiredBy: 'MQA Self-Review',
    completeness: 100,
    readySources: 2,
    totalSources: 2,
    sources: [
      {
        id: 'intervention-queue',
        label: 'From: Student Readiness',
        sourcePage: '/university/student-readiness',
        title: 'Intervention Queue records - 12 active, 8 pending assignment, owner-tracked',
        updated: 'Last updated: today',
        status: 'ready',
        action: 'View source',
        icon: 'check',
      },
      {
        id: 'outcome-tracking',
        label: 'From: Student Readiness',
        sourcePage: '/university/student-readiness',
        title: 'Hidden Employability Risk cohort - outcome tracking for 34 flagged students',
        updated: 'Last updated: today',
        status: 'ready',
        action: 'View source',
        icon: 'check',
      },
    ],
  },
}

export const timelineSubmissions = [
  {
    id: 'qs',
    title: 'QS World Rankings 2025',
    due: 'Due: 6 weeks',
    ready: '41/50 evidence points ready',
    progress: 82,
    action: 'Generate draft',
    tone: 'urgent',
  },
  {
    id: 'mqa',
    title: 'MQA Self-Review 2025',
    due: 'Due: 14 weeks',
    ready: '33/50 evidence points ready',
    progress: 65,
    action: 'Continue preparing',
    tone: 'blue',
  },
  {
    id: 'aacsb',
    title: 'AACSB Accreditation Cycle 2026',
    due: 'Due: 11 months',
    ready: '14/50 evidence points ready',
    progress: 28,
    action: 'Start early',
    tone: 'gray',
  },
]
